languageCode = "en-us"
title = "Latte, Jed?"
baseurl = "http://lattejed.com/"
uglyURLs = false

[params]
    author = "Matthew Smith"
    themeColor = "theme-base-08"
    description = "Site description"

